# Project information
site_name: Random Functions
site_url: https://bipinkrishnan.github.io/random-functions
site_description: A python library to ease out developer lives

site_author: Bipin Krishnan P

# Repository
repo_url: https://github.com/bipinKrishnan/random-functions
repo_name: bipinKrishnan/random-functions
edit_uri: "tree/main/docs"

# Configuration
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  icon:
    repo: fontawesome/brands/github

# Extensions
markdown_extensions:
  - pymdownx.superfences

# Plugins
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
